[project]
name = "passwordhasher"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "fastapi>=0.118.0",
    "passlib[argon2]>=1.7.4",
    "pydantic>=2.11.10",
    "uvicorn>=0.37.0",
]
