[project]
name = "getting-started"
version = "0.1.0"
description = "A simple FastAPI application"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "fastapi>=0.118.0",
    "uvicorn>=0.37.0",
]
